In [1]:
import pandas as pd

In [2]:
df = pd.read_csv(r"c:\Users\hdg01\Downloads\startup_funding.csv")
df.head()

,Sr No,Date dd/mm/yyyy,Startup Name,Industry Vertical,SubVertical,City Location,Investors Name,InvestmentnType,Amount in USD,Remarks
0,1,09/01/2020,BYJU’S,E-Tech,E-learning,Bengaluru,Tiger Global Management,Private Equity Round,"20,00,00,000",NaN
1,2,13/01/2020,Shuttl,Transportation,App based shuttle service,Gurgaon,Susquehanna Growth Equity,Series C,"80,48,394",NaN
2,3,09/01/2020,Mamaearth,E-commerce,Retailer of baby and toddler products,Bengaluru,Sequoia Capital India,Series B,"1,83,58,860",NaN
3,4,02/01/2020,https://www.wealthbucket.in/,FinTech,Online Investment,New Delhi,Vinod Khatumal,Pre-series A,"30,00,000",NaN
4,5,02/01/2020,Fashor,Fashion and Apparel,Embroiled Clothes For Women,Mumbai,Sprout Venture Partners,Seed Round,"18,00,000",NaN

In [3]:
df[['Date dd/mm/yyyy']]

     Date dd/mm/yyyy
0         09/01/2020
1         13/01/2020
2         09/01/2020
3         02/01/2020
4         02/01/2020
...              ...
3039      29/01/2015
3040      29/01/2015
3041      30/01/2015
3042      30/01/2015
3043      31/01/2015

[3044 rows x 1 columns]

In [4]:
df['Date dd/mm/yyyy'] = pd.to_datetime(df['Date dd/mm/yyyy'], format='%d/%m/%Y', errors='coerce')
df.head()

,Sr No,Date dd/mm/yyyy,Startup Name,Industry Vertical,SubVertical,City Location,Investors Name,InvestmentnType,Amount in USD,Remarks
0,1,2020-01-09,BYJU’S,E-Tech,E-learning,Bengaluru,Tiger Global Management,Private Equity Round,"20,00,00,000",NaN
1,2,2020-01-13,Shuttl,Transportation,App based shuttle service,Gurgaon,Susquehanna Growth Equity,Series C,"80,48,394",NaN
2,3,2020-01-09,Mamaearth,E-commerce,Retailer of baby and toddler products,Bengaluru,Sequoia Capital India,Series B,"1,83,58,860",NaN
3,4,2020-01-02,https://www.wealthbucket.in/,FinTech,Online Investment,New Delhi,Vinod Khatumal,Pre-series A,"30,00,000",NaN
4,5,2020-01-02,Fashor,Fashion and Apparel,Embroiled Clothes For Women,Mumbai,Sprout Venture Partners,Seed Round,"18,00,000",NaN

In [6]:
df.dtypes

Sr No                         int64
Date dd/mm/yyyy      datetime64[ns]
Startup Name                 object
Industry Vertical            object
SubVertical                  object
City  Location               object
Investors Name               object
InvestmentnType              object
Amount in USD                object
Remarks                      object
dtype: object

In [8]:
df.rename(columns={'Date dd/mm/yyyy': 'Date','Startup Name':'Name','Industry Vertical':'Industry','SubVertical':'Market_Segment','City  Location':'Location','Investors Name':'Investors','InvestmentnType':'Investmentn_Type','Amount in USD':'Amount'}, inplace=True)
df

,Sr No,Date,Name,Industry,Market_Segment,Location,Investors,Investmentn_Type,Amount,Remarks
0,1,2020-01-09,BYJU’S,E-Tech,E-learning,Bengaluru,Tiger Global Management,Private Equity Round,"20,00,00,000",NaN
1,2,2020-01-13,Shuttl,Transportation,App based shuttle service,Gurgaon,Susquehanna Growth Equity,Series C,"80,48,394",NaN
2,3,2020-01-09,Mamaearth,E-commerce,Retailer of baby and toddler products,Bengaluru,Sequoia Capital India,Series B,"1,83,58,860",NaN
3,4,2020-01-02,https://www.wealthbucket.in/,FinTech,Online Investment,New Delhi,Vinod Khatumal,Pre-series A,"30,00,000",NaN
4,5,2020-01-02,Fashor,Fashion and Apparel,Embroiled Clothes For Women,Mumbai,Sprout Venture Partners,Seed Round,"18,00,000",NaN
...,...,...,...,...,...,...,...,...,...,...
3039,3040,2015-01-29,Printvenue,NaN,NaN,NaN,Asia Pacific Internet Group,Private Equity,"45,00,000",NaN
3040,3041,2015-01-29,Graphene,NaN,NaN,NaN,KARSEMVEN Fund,Private Equity,"8,25,000",Govt backed VC Fund
3041,3042,2015-01-30,Mad Street Den,NaN,NaN,NaN,"Exfinity Fund, GrowX Ventures.",Private Equity,"15,00,000",NaN
3042,3043,2015-01-30,Simplotel,NaN,NaN,NaN,MakeMyTrip,Private Equity,NaN,"Strategic Funding, Minority stake"
3043,3044,2015-01-31,couponmachine.in,NaN,NaN,NaN,UK based Group of Angel Investors,Seed Funding,"1,40,000",NaN

In [9]:
df = df.drop(columns='Sr No')

In [10]:
df

,Date,Name,Industry,Market_Segment,Location,Investors,Investmentn_Type,Amount,Remarks
0,2020-01-09,BYJU’S,E-Tech,E-learning,Bengaluru,Tiger Global Management,Private Equity Round,"20,00,00,000",NaN
1,2020-01-13,Shuttl,Transportation,App based shuttle service,Gurgaon,Susquehanna Growth Equity,Series C,"80,48,394",NaN
2,2020-01-09,Mamaearth,E-commerce,Retailer of baby and toddler products,Bengaluru,Sequoia Capital India,Series B,"1,83,58,860",NaN
3,2020-01-02,https://www.wealthbucket.in/,FinTech,Online Investment,New Delhi,Vinod Khatumal,Pre-series A,"30,00,000",NaN
4,2020-01-02,Fashor,Fashion and Apparel,Embroiled Clothes For Women,Mumbai,Sprout Venture Partners,Seed Round,"18,00,000",NaN
...,...,...,...,...,...,...,...,...,...
3039,2015-01-29,Printvenue,NaN,NaN,NaN,Asia Pacific Internet Group,Private Equity,"45,00,000",NaN
3040,2015-01-29,Graphene,NaN,NaN,NaN,KARSEMVEN Fund,Private Equity,"8,25,000",Govt backed VC Fund
3041,2015-01-30,Mad Street Den,NaN,NaN,NaN,"Exfinity Fund, GrowX Ventures.",Private Equity,"15,00,000",NaN
3042,2015-01-30,Simplotel,NaN,NaN,NaN,MakeMyTrip,Private Equity,NaN,"Strategic Funding, Minority stake"
3043,2015-01-31,couponmachine.in,NaN,NaN,NaN,UK based Group of Angel Investors,Seed Funding,"1,40,000",NaN

In [11]:
df['Amount'] = df['Amount'].str.replace(',', '')
df

,Date,Name,Industry,Market_Segment,Location,Investors,Investmentn_Type,Amount,Remarks
0,2020-01-09,BYJU’S,E-Tech,E-learning,Bengaluru,Tiger Global Management,Private Equity Round,200000000,NaN
1,2020-01-13,Shuttl,Transportation,App based shuttle service,Gurgaon,Susquehanna Growth Equity,Series C,8048394,NaN
2,2020-01-09,Mamaearth,E-commerce,Retailer of baby and toddler products,Bengaluru,Sequoia Capital India,Series B,18358860,NaN
3,2020-01-02,https://www.wealthbucket.in/,FinTech,Online Investment,New Delhi,Vinod Khatumal,Pre-series A,3000000,NaN
4,2020-01-02,Fashor,Fashion and Apparel,Embroiled Clothes For Women,Mumbai,Sprout Venture Partners,Seed Round,1800000,NaN
...,...,...,...,...,...,...,...,...,...
3039,2015-01-29,Printvenue,NaN,NaN,NaN,Asia Pacific Internet Group,Private Equity,4500000,NaN
3040,2015-01-29,Graphene,NaN,NaN,NaN,KARSEMVEN Fund,Private Equity,825000,Govt backed VC Fund
3041,2015-01-30,Mad Street Den,NaN,NaN,NaN,"Exfinity Fund, GrowX Ventures.",Private Equity,1500000,NaN
3042,2015-01-30,Simplotel,NaN,NaN,NaN,MakeMyTrip,Private Equity,NaN,"Strategic Funding, Minority stake"
3043,2015-01-31,couponmachine.in,NaN,NaN,NaN,UK based Group of Angel Investors,Seed Funding,140000,NaN

In [12]:
df.shape

(3044, 9)

In [13]:
df = df.dropna(subset=['Amount'])
df

,Date,Name,Industry,Market_Segment,Location,Investors,Investmentn_Type,Amount,Remarks
0,2020-01-09,BYJU’S,E-Tech,E-learning,Bengaluru,Tiger Global Management,Private Equity Round,200000000,NaN
1,2020-01-13,Shuttl,Transportation,App based shuttle service,Gurgaon,Susquehanna Growth Equity,Series C,8048394,NaN
2,2020-01-09,Mamaearth,E-commerce,Retailer of baby and toddler products,Bengaluru,Sequoia Capital India,Series B,18358860,NaN
3,2020-01-02,https://www.wealthbucket.in/,FinTech,Online Investment,New Delhi,Vinod Khatumal,Pre-series A,3000000,NaN
4,2020-01-02,Fashor,Fashion and Apparel,Embroiled Clothes For Women,Mumbai,Sprout Venture Partners,Seed Round,1800000,NaN
...,...,...,...,...,...,...,...,...,...
3038,2015-01-28,Grabhouse.com,NaN,NaN,NaN,"Kalaari Capital, Sequoia Capital",Private Equity,2500000,Series A
3039,2015-01-29,Printvenue,NaN,NaN,NaN,Asia Pacific Internet Group,Private Equity,4500000,NaN
3040,2015-01-29,Graphene,NaN,NaN,NaN,KARSEMVEN Fund,Private Equity,825000,Govt backed VC Fund
3041,2015-01-30,Mad Street Den,NaN,NaN,NaN,"Exfinity Fund, GrowX Ventures.",Private Equity,1500000,NaN
3043,2015-01-31,couponmachine.in,NaN,NaN,NaN,UK based Group of Angel Investors,Seed Funding,140000,NaN

In [16]:
df['Amount'] = df['Amount'].str.replace(r'\\xc2\\xa0', '', regex=True)

C:\Users\hdg01\AppData\Local\Temp\ipykernel_16624\3634642339.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Amount'] = df['Amount'].str.replace(r'\\xc2\\xa0', '', regex=True)

,Date,Name,Industry,Market_Segment,Location,Investors,Investmentn_Type,Amount,Remarks
0,2020-01-09,BYJU’S,E-Tech,E-learning,Bengaluru,Tiger Global Management,Private Equity Round,200000000,NaN
1,2020-01-13,Shuttl,Transportation,App based shuttle service,Gurgaon,Susquehanna Growth Equity,Series C,8048394,NaN
2,2020-01-09,Mamaearth,E-commerce,Retailer of baby and toddler products,Bengaluru,Sequoia Capital India,Series B,18358860,NaN
3,2020-01-02,https://www.wealthbucket.in/,FinTech,Online Investment,New Delhi,Vinod Khatumal,Pre-series A,3000000,NaN
4,2020-01-02,Fashor,Fashion and Apparel,Embroiled Clothes For Women,Mumbai,Sprout Venture Partners,Seed Round,1800000,NaN
...,...,...,...,...,...,...,...,...,...
3038,2015-01-28,Grabhouse.com,NaN,NaN,NaN,"Kalaari Capital, Sequoia Capital",Private Equity,2500000,Series A
3039,2015-01-29,Printvenue,NaN,NaN,NaN,Asia Pacific Internet Group,Private Equity,4500000,NaN
3040,2015-01-29,Graphene,NaN,NaN,NaN,KARSEMVEN Fund,Private Equity,825000,Govt backed VC Fund
3041,2015-01-30,Mad Street Den,NaN,NaN,NaN,"Exfinity Fund, GrowX Ventures.",Private Equity,1500000,NaN
3043,2015-01-31,couponmachine.in,NaN,NaN,NaN,UK based Group of Angel Investors,Seed Funding,140000,NaN

In [18]:
df = df.drop(columns=['Remarks'])

In [28]:
df.rename(columns={'Investmentn_Type':'Investment_Type'}, inplace=True)

In [20]:
df['Name'] = df['Name'].str.replace(r'\\xc2\\xa0', '', regex=True)

In [21]:
df['Industry'] = df['Industry'].str.replace(r'\\xc2\\xa0', '', regex=True)

In [22]:
df['Market_Segment'] = df['Market_Segment'].str.replace(r'\\xc2\\xa0', '', regex=True)

In [23]:
df['Location'] = df['Location'].str.replace(r'\\xc2\\xa0', '', regex=True)

In [24]:
df['Investors'] = df['Investors'].str.replace(r'\\xc2\\xa0', '', regex=True)

In [31]:
df['Investment_Type'] = df['Investment_Type'].str.replace(r'\\xc2\\xa0', '', regex=True)

In [37]:
df

,Date,Name,Industry,Market_Segment,Location,Investors,Investment_Type,Amount
0,2020-01-09,BYJU’S,E-Tech,E-learning,Bengaluru,Tiger Global Management,Private Equity Round,200000000
1,2020-01-13,Shuttl,Transportation,App based shuttle service,Gurgaon,Susquehanna Growth Equity,Series C,8048394
2,2020-01-09,Mamaearth,E-commerce,Retailer of baby and toddler products,Bengaluru,Sequoia Capital India,Series B,18358860
3,2020-01-02,https://www.wealthbucket.in/,FinTech,Online Investment,New Delhi,Vinod Khatumal,Pre-series A,3000000
4,2020-01-02,Fashor,Fashion and Apparel,Embroiled Clothes For Women,Mumbai,Sprout Venture Partners,Seed Round,1800000
...,...,...,...,...,...,...,...,...
3038,2015-01-28,Grabhouse.com,NaN,NaN,NaN,"Kalaari Capital, Sequoia Capital",Private Equity,2500000
3039,2015-01-29,Printvenue,NaN,NaN,NaN,Asia Pacific Internet Group,Private Equity,4500000
3040,2015-01-29,Graphene,NaN,NaN,NaN,KARSEMVEN Fund,Private Equity,825000
3041,2015-01-30,Mad Street Den,NaN,NaN,NaN,"Exfinity Fund, GrowX Ventures.",Private Equity,1500000
3043,2015-01-31,couponmachine.in,NaN,NaN,NaN,UK based Group of Angel Investors,Seed Funding,140000

In [38]:
df.isnull().sum()

Date                 7
Name                 0
Industry           131
Market_Segment     658
Location           135
Investors           20
Investment_Type      3
Amount               0
dtype: int64

In [41]:
df['Industry'].fillna('Unknown', inplace=True)
df

,Date,Name,Industry,Market_Segment,Location,Investors,Investment_Type,Amount
0,2020-01-09,BYJU’S,E-Tech,E-learning,Bengaluru,Tiger Global Management,Private Equity Round,200000000
1,2020-01-13,Shuttl,Transportation,App based shuttle service,Gurgaon,Susquehanna Growth Equity,Series C,8048394
2,2020-01-09,Mamaearth,E-commerce,Retailer of baby and toddler products,Bengaluru,Sequoia Capital India,Series B,18358860
3,2020-01-02,https://www.wealthbucket.in/,FinTech,Online Investment,New Delhi,Vinod Khatumal,Pre-series A,3000000
4,2020-01-02,Fashor,Fashion and Apparel,Embroiled Clothes For Women,Mumbai,Sprout Venture Partners,Seed Round,1800000
...,...,...,...,...,...,...,...,...
3038,2015-01-28,Grabhouse.com,Unknown,NaN,NaN,"Kalaari Capital, Sequoia Capital",Private Equity,2500000
3039,2015-01-29,Printvenue,Unknown,NaN,NaN,Asia Pacific Internet Group,Private Equity,4500000
3040,2015-01-29,Graphene,Unknown,NaN,NaN,KARSEMVEN Fund,Private Equity,825000
3041,2015-01-30,Mad Street Den,Unknown,NaN,NaN,"Exfinity Fund, GrowX Ventures.",Private Equity,1500000
3043,2015-01-31,couponmachine.in,Unknown,NaN,NaN,UK based Group of Angel Investors,Seed Funding,140000

In [43]:
df['Market_Segment'].fillna('Unknown', inplace=True)
df

,Date,Name,Industry,Market_Segment,Location,Investors,Investment_Type,Amount
0,2020-01-09,BYJU’S,E-Tech,E-learning,Bengaluru,Tiger Global Management,Private Equity Round,200000000
1,2020-01-13,Shuttl,Transportation,App based shuttle service,Gurgaon,Susquehanna Growth Equity,Series C,8048394
2,2020-01-09,Mamaearth,E-commerce,Retailer of baby and toddler products,Bengaluru,Sequoia Capital India,Series B,18358860
3,2020-01-02,https://www.wealthbucket.in/,FinTech,Online Investment,New Delhi,Vinod Khatumal,Pre-series A,3000000
4,2020-01-02,Fashor,Fashion and Apparel,Embroiled Clothes For Women,Mumbai,Sprout Venture Partners,Seed Round,1800000
...,...,...,...,...,...,...,...,...
3038,2015-01-28,Grabhouse.com,Unknown,Unknown,NaN,"Kalaari Capital, Sequoia Capital",Private Equity,2500000
3039,2015-01-29,Printvenue,Unknown,Unknown,NaN,Asia Pacific Internet Group,Private Equity,4500000
3040,2015-01-29,Graphene,Unknown,Unknown,NaN,KARSEMVEN Fund,Private Equity,825000
3041,2015-01-30,Mad Street Den,Unknown,Unknown,NaN,"Exfinity Fund, GrowX Ventures.",Private Equity,1500000
3043,2015-01-31,couponmachine.in,Unknown,Unknown,NaN,UK based Group of Angel Investors,Seed Funding,140000

In [45]:
df['Location'].fillna('Unknown', inplace=True)
df

,Date,Name,Industry,Market_Segment,Location,Investors,Investment_Type,Amount
0,2020-01-09,BYJU’S,E-Tech,E-learning,Bengaluru,Tiger Global Management,Private Equity Round,200000000
1,2020-01-13,Shuttl,Transportation,App based shuttle service,Gurgaon,Susquehanna Growth Equity,Series C,8048394
2,2020-01-09,Mamaearth,E-commerce,Retailer of baby and toddler products,Bengaluru,Sequoia Capital India,Series B,18358860
3,2020-01-02,https://www.wealthbucket.in/,FinTech,Online Investment,New Delhi,Vinod Khatumal,Pre-series A,3000000
4,2020-01-02,Fashor,Fashion and Apparel,Embroiled Clothes For Women,Mumbai,Sprout Venture Partners,Seed Round,1800000
...,...,...,...,...,...,...,...,...
3038,2015-01-28,Grabhouse.com,Unknown,Unknown,Unknown,"Kalaari Capital, Sequoia Capital",Private Equity,2500000
3039,2015-01-29,Printvenue,Unknown,Unknown,Unknown,Asia Pacific Internet Group,Private Equity,4500000
3040,2015-01-29,Graphene,Unknown,Unknown,Unknown,KARSEMVEN Fund,Private Equity,825000
3041,2015-01-30,Mad Street Den,Unknown,Unknown,Unknown,"Exfinity Fund, GrowX Ventures.",Private Equity,1500000
3043,2015-01-31,couponmachine.in,Unknown,Unknown,Unknown,UK based Group of Angel Investors,Seed Funding,140000

In [47]:
df['Investors'].fillna('Unknown', inplace=True)
df

,Date,Name,Industry,Market_Segment,Location,Investors,Investment_Type,Amount
0,2020-01-09,BYJU’S,E-Tech,E-learning,Bengaluru,Tiger Global Management,Private Equity Round,200000000
1,2020-01-13,Shuttl,Transportation,App based shuttle service,Gurgaon,Susquehanna Growth Equity,Series C,8048394
2,2020-01-09,Mamaearth,E-commerce,Retailer of baby and toddler products,Bengaluru,Sequoia Capital India,Series B,18358860
3,2020-01-02,https://www.wealthbucket.in/,FinTech,Online Investment,New Delhi,Vinod Khatumal,Pre-series A,3000000
4,2020-01-02,Fashor,Fashion and Apparel,Embroiled Clothes For Women,Mumbai,Sprout Venture Partners,Seed Round,1800000
...,...,...,...,...,...,...,...,...
3038,2015-01-28,Grabhouse.com,Unknown,Unknown,Unknown,"Kalaari Capital, Sequoia Capital",Private Equity,2500000
3039,2015-01-29,Printvenue,Unknown,Unknown,Unknown,Asia Pacific Internet Group,Private Equity,4500000
3040,2015-01-29,Graphene,Unknown,Unknown,Unknown,KARSEMVEN Fund,Private Equity,825000
3041,2015-01-30,Mad Street Den,Unknown,Unknown,Unknown,"Exfinity Fund, GrowX Ventures.",Private Equity,1500000
3043,2015-01-31,couponmachine.in,Unknown,Unknown,Unknown,UK based Group of Angel Investors,Seed Funding,140000

In [50]:
df['Investment_Type'].fillna('Unknown', inplace=True)
df

,Date,Name,Industry,Market_Segment,Location,Investors,Investment_Type,Amount
0,2020-01-09,BYJU’S,E-Tech,E-learning,Bengaluru,Tiger Global Management,Private Equity Round,200000000
1,2020-01-13,Shuttl,Transportation,App based shuttle service,Gurgaon,Susquehanna Growth Equity,Series C,8048394
2,2020-01-09,Mamaearth,E-commerce,Retailer of baby and toddler products,Bengaluru,Sequoia Capital India,Series B,18358860
3,2020-01-02,https://www.wealthbucket.in/,FinTech,Online Investment,New Delhi,Vinod Khatumal,Pre-series A,3000000
4,2020-01-02,Fashor,Fashion and Apparel,Embroiled Clothes For Women,Mumbai,Sprout Venture Partners,Seed Round,1800000
...,...,...,...,...,...,...,...,...
3038,2015-01-28,Grabhouse.com,Unknown,Unknown,Unknown,"Kalaari Capital, Sequoia Capital",Private Equity,2500000
3039,2015-01-29,Printvenue,Unknown,Unknown,Unknown,Asia Pacific Internet Group,Private Equity,4500000
3040,2015-01-29,Graphene,Unknown,Unknown,Unknown,KARSEMVEN Fund,Private Equity,825000
3041,2015-01-30,Mad Street Den,Unknown,Unknown,Unknown,"Exfinity Fund, GrowX Ventures.",Private Equity,1500000
3043,2015-01-31,couponmachine.in,Unknown,Unknown,Unknown,UK based Group of Angel Investors,Seed Funding,140000

In [51]:
df

,Date,Name,Industry,Market_Segment,Location,Investors,Investment_Type,Amount
0,2020-01-09,BYJU’S,E-Tech,E-learning,Bengaluru,Tiger Global Management,Private Equity Round,200000000
1,2020-01-13,Shuttl,Transportation,App based shuttle service,Gurgaon,Susquehanna Growth Equity,Series C,8048394
2,2020-01-09,Mamaearth,E-commerce,Retailer of baby and toddler products,Bengaluru,Sequoia Capital India,Series B,18358860
3,2020-01-02,https://www.wealthbucket.in/,FinTech,Online Investment,New Delhi,Vinod Khatumal,Pre-series A,3000000
4,2020-01-02,Fashor,Fashion and Apparel,Embroiled Clothes For Women,Mumbai,Sprout Venture Partners,Seed Round,1800000
...,...,...,...,...,...,...,...,...
3038,2015-01-28,Grabhouse.com,Unknown,Unknown,Unknown,"Kalaari Capital, Sequoia Capital",Private Equity,2500000
3039,2015-01-29,Printvenue,Unknown,Unknown,Unknown,Asia Pacific Internet Group,Private Equity,4500000
3040,2015-01-29,Graphene,Unknown,Unknown,Unknown,KARSEMVEN Fund,Private Equity,825000
3041,2015-01-30,Mad Street Den,Unknown,Unknown,Unknown,"Exfinity Fund, GrowX Ventures.",Private Equity,1500000
3043,2015-01-31,couponmachine.in,Unknown,Unknown,Unknown,UK based Group of Angel Investors,Seed Funding,140000

In [52]:
df = df.to_csv('StartUps_In_India.csv')